services:
  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: unless-stopped
    env_file:
      - /home/azureuser/lab/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastify-app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - /home/azureuser/lab/.env
    ports:
      - "127.0.0.1:3000:3000"
    volumes: 
       - /home/azureuser/pictures:/app/pictures 
    networks:
      - backend

volumes:
  pgdata:
  picturesv:

networks:
  backend:
    driver: bridge
